# Generated by Django 4.1.7 on 2023-03-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='auther',
        ),
        migrations.RemoveField(
            model_name='book',
            name='follow_auther',
        ),
    ]
